version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testpw
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
